window.I18N = {
  tr: {
    title: "Sema Hoca ile Hızlı Okuma Egzersizi",
    tab_premade: "📄 Hazır Metin & Dosya",
    tab_custom: "🕮/🔗 Özel Metin & URL",
    choose_preset: "Hazır metin seç…",
    url_placeholder: "https://site.com/makale",
    btn_fetch: "URL içeriğini ekle",
    use_text_here: "Buradaki metni kullan",
    custom_placeholder: "Veya özel metninizi buraya yapıştırın…",
    settings: "Ayarlar",
    shuffle: "Karıştır",
    tts: "Sesli okuma (≤ 60 KPM)",
    focus_mode: "Okuma Odağı",
    voice: "Ses",
    female: "Kadın Sesi",
    male: "Erkek Sesi",
    speed: "Hız (KPM)",
    num_words: "Kelime adeti",
    font: "Font (rem)",
    start: "Başlat",
    restart: "Baştan",
    zoom_in: "🔍 Büyüt",
    zoom_out: "↩︎ Küçült",
    help_title: "Kontrol Düğmeleri:",
    help_url: "URL içeriğini ekle: Linkteki metni “Özel metin” kutusuna ekler.",
    help_custom: "Özel metin: Kendi metninizi yapıştırarak pratik yapın.",
    help_file: "Hazır metin/Dosya: Hazır metin seçin veya .txt/.csv yükleyin.",
    help_shuffle: "Karıştır: Kelimelerin sırasını rastgele karıştırır.",
    help_tts: "Sesli okuma: Düşük hızlarda etkilidir.",
    help_play: "Başlat/Duraklat/Devam: Okumayı kontrol eder.",
    help_restart: "Baştan: Metnin başına döner.",
    help_zoom: "🔍 Büyüt / ↩︎ Küçült: Odak için tam ekran."
  },
  en: {
    title: "Speed Reading Exercise with Sema Hoca",
    tab_premade: "📄 Pre-made Text & File",
    tab_custom: "🕮/🔗 Custom Text & URL",
    choose_preset: "Choose a preset…",
    url_placeholder: "https://site.com/article",
    btn_fetch: "Add URL content",
    use_text_here: "Use the text here",
    custom_placeholder: "Or paste your custom text here…",
    settings: "Settings",
    shuffle: "Shuffle",
    tts: "Text-to-Speech (≤ 60 WPM)",
    focus_mode: "Focus Line",
    voice: "Voice",
    female: "Female",
    male: "Male",
    speed: "Speed (WPM)",
    num_words: "Words shown",
    font: "Font (rem)",
    start: "Start",
    restart: "Restart",
    zoom_in: "🔍 Zoom",
    zoom_out: "↩︎ Exit",
    help_title: "Controls:",
    help_url: "Add URL content: extracts text to the custom box.",
    help_custom: "Custom text: paste any text and practice.",
    help_file: "Pre-made/File: choose a preset or upload .txt/.csv.",
    help_shuffle: "Shuffle: randomize word order.",
    help_tts: "TTS: works best at low speeds.",
    help_play: "Start/Pause/Resume: control playback.",
    help_restart: "Restart: go back to the beginning.",
    help_zoom: "🔍 Zoom / ↩︎ Exit: full-screen focus."
  }
};

